### ISSUE TITLE
About model_22 from week 6

### ISSUE THREAD

**Issue by rosgori** [gbosquechacon/statrethinking_winter2019#1]
You wrote

> Results are quite different from the original in R. I can't seem to locate the issue. Parameter g should be much higher, around 0.28 and its HPD interval should be completely above zero to prove the point that we see a gender advantage when in reality there is none.

They are different because the code in R has a seed (`set.seed(1913)`) and that changes the number for `g` and `d`. If you rerun that model (changing `G, S, D, A`), the numbes will be almost the same.

**Comment by gbosquechacon** [comment]
Oh man thanks so much! I'll make sure to update the notebook this weekend : )

**Comment by gbosquechacon** [comment]
Fix added to the week 6 notebook.
